In [1]:
import numpy as np

iterable

An iterable is any Python object capable of returning its members one at a time, permitting it to be iterated over in a for-loop. Familiar examples of iterables include lists, tuples, and strings - any such sequence can be iterated over in a for-loop.

This session covers a set of methods we had parked for laters
map
lambda
lapply

In [1]:
# say there is a function
def numSq(x):
    return x**2

# and let there be a iterable 
# (lists, arrays etc are called iterables as we can iterate one element at a time)
x = [1,2,3]

In [2]:
# when we get a complex object like this one Python does not automatically display.
# using list() solves that problem
m = map(numSq,x)
for i in m:
    print(i)

1
4
9


In [5]:
def aa(v):
    return v*2
v = [1,2,3]
m =map(aa,v)
for i in m:
    print(i)


2
4
6


In [4]:
list(map(numSq,x))

[1, 4, 9]

In [5]:
# this is a simple function. however, this can be ANY function.

In [6]:
# one more example, say a teacher wants to award 2 marks more
def correction(old_marks):
    return old_marks + 2

# old_marks
old_marks = np.array([65,75,85])

list(map(correction, old_marks))

[67, 77, 87]

In [34]:
def even_odd(n):
    if (n%2==0):
        out = "even"
    else:
        out = "odd"
    return out

In [37]:
arr = np.array([1,2,3])

In [9]:
even_odd(1)

'odd'

In [39]:
import numpy as np
for i in np.array(arr):
    print(even_odd(i))

odd
even
odd


In [40]:
arr = [1,2,3]
list(map(even_odd,arr))

['odd', 'even', 'odd']

Filter

filter(func, iterable)

This is like map() with a twist

filter() requires the function to return boolean values (true or false)
It will evaluate each element of the iterable using the function, which will return T or F.
These T or F will be used to logically subset the iterable.

In [7]:
import numpy as np
arr = np.array([0,2,3,4,-1,6])

In [8]:
# what is logical subset?
arr[arr>=0]

array([0, 2, 3, 4, 6])

In [13]:
arr > 0

array([False,  True,  True,  True, False,  True])

In [14]:
arr[arr>0]

array([2, 3, 4, 6])

In [10]:
def pos_filter(n):
    return (n>=0)

In [11]:
arr = np.array([0,2,3,4,-1,6])
list(filter(pos_filter,arr))

[0, 2, 3, 4, 6]

In [16]:
arr[pos_filter(arr)]

array([0, 2, 3, 4, 6])

In [5]:
def hot_not(temp):
    if temp > 40:
        return True
    else:
        return False

    
temp = [41,39,25,42]

In [6]:
def hot_not (temp):
    return temp>40
list(map(hot_not,temp))

[True, False, False, True]

In [65]:
temp_arr = np.array(temp)
temp_arr[temp_arr>40]

array([41, 42])

In [19]:
list(map(hot_not,temp))

[True, False, False, True]

In [20]:
# this is an iterable
scores = [66, 90, 68, 59, 76, 60, 88, 74, 81, 65]

# this is a function
def is_A_student(score):
    return score > 75

# filter(func, iterable) will return parts of the iterable which satisfy the func condition

over_75 = list(filter(is_A_student, scores))

print(over_75)

[90, 76, 88, 81]


In [21]:
scores = np.array(scores)
scores [scores > 75]

array([90, 76, 88, 81])

In [22]:
# the same result can be achieved using a for loop also
out = []
for i in scores:
    if i > 75:
        out.append(i)
out

[90, 76, 88, 81]

In [23]:
len(scores)

10

In [66]:
# one more way
import numpy as np
arr = np.array(scores)
arr[arr > 75]

array([90, 76, 88, 81])

In [67]:
# subsetting is not possible directly in lists using condition
# there are equivalents like mentioned in 
# https://stackoverflow.com/questions/9542738/python-find-in-list

scores[arr > 75]

array([90, 76, 88, 81])

In [26]:
# lambda functions (anonymous functions)

# It includes a single expression involving any number of parameters
# ideal for simply creating a funcction object where one is required (and just that)
# lambda functions always return the result of the expression so explicit return is not required

def square_it(y): 
    return y*y; 

print(square_it(5)) 

g = lambda x: x*x 
print(g(7))

25
49


In [27]:
# can we combine map and lambda?
# all we are doing is defining a nameless function inside map itself instead of outside

list(map(lambda y: y+2, old_marks))

[67, 77, 87]

In [28]:
list(filter(lambda y: y>40, temp))

[41, 42]

In [29]:
x = [1,2,3]
import pandas as pd
pd.Series(x).apply(lambda num: num**2)

0    1
1    4
2    9
dtype: int64

In [30]:
pd.Series(x).apply(correction)

0    3
1    4
2    5
dtype: int64

In [31]:
# Exercise
# create a dataframe with two numeric columns with height in cms and weight in gms
# using this example, calculate the height in m and weight in kg

In [32]:
y = lambda x: x*x 
y(2)

4

In [33]:
x = [1,2,3]
import pandas as pd
pd.Series(x)**2

0    1
1    4
2    9
dtype: int64

In [23]:
prav ="praveen"
for p in prav:
   
       

p
r
a
v
e
e
e
e
n
