In [2]:
import numpy as np

In [6]:
arraya = np.array([1,2,3,4,5])
print(arraya[1:5])

[2 3 4 5]


In [16]:
x =[4,6,8,10,2]
y =[2,1,2,2,2]
arx = np.array(x)
ary = np.array(y)
arx/ary
ary**2

array([4, 1, 4, 4, 4])

In [95]:
random_vector = np.random.randint([1,101,10],200)
print(random_vector)

[137 136 191]


In [38]:
random_vector = np.random.rand(5,7)
print(random_vector)

[[0.43468512 0.07893486 0.41470233 0.91045555 0.34826903 0.14644036
  0.73148673]
 [0.75657535 0.52169168 0.01021333 0.54111233 0.21362862 0.85578031
  0.73891961]
 [0.68183651 0.1441875  0.49504587 0.41077452 0.29676523 0.5475649
  0.64982694]
 [0.6569487  0.10498536 0.35281741 0.14977709 0.84377295 0.83536195
  0.00877809]
 [0.32564517 0.20290266 0.10188984 0.1275543  0.92854323 0.47177706
  0.91139992]]


In [45]:
vec = np.array([2,4,6,7,8])
constant = 10
newvec = np.zeros_like(vec)

for i in range(len(vec)):
    newvec[i]=vec[i]/2
newvec

array([1, 2, 3, 3, 4])

In [55]:
mat1 =np.array([[1,2],[3,4]])
mat2 =np.array([np.random.randint(1,4,4)])
print(mat1)
mat2= mat2.reshape(2,2)
print(mat2)

r = np.dot(mat1,mat2)
print(r)


[[1 2]
 [3 4]]
[[1 2]
 [2 2]]
[[ 5  6]
 [11 14]]


In [78]:
z=np.zeros([10])
z = np.zeros([10,10])
print(z.size)
z = np.arange(50,55,4)
print(z)
z = z[::-1]
print(z)

100
[50 54]
[54 50]


In [80]:
z  = np.eye(2)
print(z)


[[1. 0.]
 [0. 1.]]


In [117]:
z1= np.random.randint(1,100,30)
m = z1.mean()
print(m)



49.63333333333333
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [118]:

students = np.arange(1, 31)

students = students.reshape(5, 6)
print(students)
teams = students.T
print(teams)

for index,i in enumerate(teams):
    print("teams",teams[index])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
[[ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]
 [ 6 12 18 24 30]]
teams [ 1  7 13 19 25]
teams [ 2  8 14 20 26]
teams [ 3  9 15 21 27]
teams [ 4 10 16 22 28]
teams [ 5 11 17 23 29]
teams [ 6 12 18 24 30]


In [3]:

a = [1, 2, 3, 4]

print("Original array")
print(a)
x = np.asfarray(a)
print("Array converted to a float type:")
print(x) 

Original array
[1, 2, 3, 4]
Array converted to a float type:
[1. 2. 3. 4.]


In [9]:
a = np.ones(25)
a= a.reshape(5,5)
a[1:-1,1:-1]=0
print(a)







[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:


x = np.empty((3, 4))

print(x)

y = np.full((3, 3), 6)

print(y)

[[1.44266411e-311 2.42092166e-322 0.00000000e+000 0.00000000e+000]
 [1.10343781e-312 2.92966904e-033 5.27847958e-091 4.27969631e-037]
 [2.36689554e+179 3.12453507e-033 6.99196248e+228 1.42320287e+160]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [19]:


fvalues = [0, 12, 45.21, 34, 99.91, 32]

F = np.array(fvalues)

print("Values in Fahrenheit degrees:")
print(F)

print("Values in  Centigrade degrees:")
final = np.round((5 * F / 9 - 5 * 32 / 9), 3)
print(final)
print(np.round(final))

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91 32.  ]
Values in  Centigrade degrees:
[-17.778 -11.111   7.339   1.111  37.728   0.   ]
[-18. -11.   7.   1.  38.   0.]


In [26]:
array1 = np.array([0, 10, 20, 40, 60,234,4234,4234,424,345,5,5,54,2,34,5,78,87,78,876,])


print("Array1: ", array1)

array2 = [10, 30, 40,456,46,23,5435,34,35353,5,543,345,53,45,54,2,34,5,78,87,78,876,7467,887,7876]

print("Array2: ", array2)

print("Common values between two arrays:")
print(np.intersect1d(array1, array2))
twodinterdect= np.intersect1d(array1, array2)
twodinterdect= twodinterdect.reshape(2,5)
print(twodinterdect)


Array1:  [   0   10   20   40   60  234 4234 4234  424  345    5    5   54    2
   34    5   78   87   78  876]
Array2:  [10, 30, 40, 456, 46, 23, 5435, 34, 35353, 5, 543, 345, 53, 45, 54, 2, 34, 5, 78, 87, 78, 876, 7467, 887, 7876]
Common values between two arrays:
[  2   5  10  34  40  54  78  87 345 876]
[[  2   5  10  34  40]
 [ 54  78  87 345 876]]


In [29]:
array1 = np.array([0, 10, 20, 40, 60, 80])


print("Array1: ", array1)


array2 = [10, 30, 40, 50, 70]

print("Array2: ", array2)


print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(array1, array2))
print("Unique values in array2 that are not in array1:")
print(np.setdiff1d(array2, array1))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values in array1 that are not in array2:
[ 0 20 60 80]
Unique values in array2 that are not in array1:
[30 50 70]


In [30]:
print(np.all([[True,False],[True,True]]))  
print(np.all([[True,True],[True,True]]))   

print(np.all([10, 20, 0, -50]))  
print(np.all([10, 20, -50]))

False
True
False
True


In [32]:
x = np.repeat(3, 4)
print(x)


x = np.array([[1, 2], [3, 4]])
print(x)

print(np.repeat(x, 2))

[3 3 3 3]
[[1 2]
 [3 4]]
[1 1 2 2 3 3 4 4]


In [33]:



def insertion_sort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and key < arr[j]:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key
    return arr

arr = np.array([12, 11, 13, 5, 6])
print("Original array:", arr)
sorted_arr = insertion_sort(arr)
print("Sorted array:", sorted_arr)


Original array: [12 11 13  5  6]
Sorted array: [ 5  6 11 12 13]


In [37]:


A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.zeros_like(A)

for i in range(A.shape[0]):
    for j in range(B.shape[1]):
        for k in range(A.shape[1]):
            result[i, j] += A[i, k] * B[k, j]

print(result)





[[19 22]
 [43 50]]


In [36]:

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = np.dot(A, B)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nResult of matrix multiplication A * B:")
print(result)


Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Result of matrix multiplication A * B:
[[19 22]
 [43 50]]


In [40]:
lst = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(lst)
print(arr)

tpl = (1,2,3,4,5)
arr = np.array(tpl)
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5]


In [41]:



arr = np.linspace(1, 10, 10)
print("Original Array:")
print(arr)


reshaped_arr = np.reshape(arr, (2, 5))
print("\nReshaped Array (2x5):")
print(reshaped_arr)


Original Array:
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

Reshaped Array (2x5):
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [4]:



arr1 = np.zeros((2, 2))
print("Original Array:")
print(arr1)


transposed_arr = arr1.T
concatenated_arr = np.concatenate((arr1, transposed_arr), axis=0)
print("\nConcatenated Array:")
print(concatenated_arr)


Original Array:
[[0. 0.]
 [0. 0.]]

Concatenated Array:
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [44]:



arr = np.arange(12)
print("Original Array:")
print(arr)

subarrays = np.split(arr, 3)
print("\nSub-arrays:",subarrays)
for i, subarray in enumerate(subarrays):
    print(f"Sub-array {i+1}: {subarray}")


Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Sub-arrays: [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
Sub-array 1: [0 1 2 3]
Sub-array 2: [4 5 6 7]
Sub-array 3: [ 8  9 10 11]


In [45]:


identity_matrix = np.eye(3)
print("Original Identity Matrix:")
print(identity_matrix)

resized_matrix = np.resize(identity_matrix, (4, 4))
print("\nResized Matrix:")
print(resized_matrix)


Original Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Resized Matrix:
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [0. 1. 0. 0.]]


In [48]:
arr = np.arange(12)

resized_matrix = np.resize(arr, (4, 4))
print("Resized Matrix:","\n",resized_matrix)

Resized Matrix: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [50]:



value = 5
arr = np.full((7, 3), value)
print("Original Array:")
print(arr)


flattened_arr = arr.flatten()
print("\nFlattened Array:")
print(flattened_arr)


Original Array:
[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]

Flattened Array:
[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]


In [65]:
arr = np.linspace(1,30,6).reshape(3,2)
print(arr)
trans = np.transpose(arr)
print(trans)


[[ 1.   6.8]
 [12.6 18.4]
 [24.2 30. ]]
[[ 1.  12.6 24.2]
 [ 6.8 18.4 30. ]]


In [63]:



arr = np.linspace(1, 10, 12).reshape(3, 4)
print("Original Array:")
print(arr)


transposed_arr = np.transpose(arr)
print("\nTransposed Array:")
print(transposed_arr)


Original Array:
[[ 1.          1.81818182  2.63636364  3.45454545]
 [ 4.27272727  5.09090909  5.90909091  6.72727273]
 [ 7.54545455  8.36363636  9.18181818 10.        ]]

Transposed Array:
[[ 1.          4.27272727  7.54545455]
 [ 1.81818182  5.09090909  8.36363636]
 [ 2.63636364  5.90909091  9.18181818]
 [ 3.45454545  6.72727273 10.        ]]


In [66]:



arr1 = np.arange(9).reshape(3, 3)
print("Original Array:")
print(arr1)

vstacked_arr = np.vstack((arr1, arr1.T))
print("\nVertically Stacked Array:")
print(vstacked_arr)


Original Array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Vertically Stacked Array:
[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 3 6]
 [1 4 7]
 [2 5 8]]


In [69]:



arr = np.zeros(10)
print("Original Array:")
print(arr)


subarrays = np.split(arr, 5)
print("\nSub-arrays:")
for i, subarray in enumerate(subarrays):
    print(f"Sub-array {i+1}: {subarray}")


Original Array:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Sub-arrays:
Sub-array 1: [0. 0.]
Sub-array 2: [0. 0.]
Sub-array 3: [0. 0.]
Sub-array 4: [0. 0.]
Sub-array 5: [0. 0.]


In [76]:


arr = np.arange(12)

reshaped_arr = np.reshape(arr, (3, 4))

print("Original Array:")
print(reshaped_arr)

print("\nElement at index (1, 2):", reshaped_arr[1,2])
print("Slice from the second row onwards:")
print(reshaped_arr[1:])


Original Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Element at index (1, 2): 6
Slice from the second row onwards:
[[ 4  5  6  7]
 [ 8  9 10 11]]


In [96]:



arr1 = np.ones((2, 3))

vstacked_arr = np.vstack((arr1, arr1 * 2))

print("Original Array:")
print(vstacked_arr)

indices = np.array([0, 2])

print("\nElements at indices 0 and 2:")
print(vstacked_arr[0:4, 0:3])


Original Array:
[[1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]
 [2. 2. 2.]]

Elements at indices 0 and 2:
[[1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [98]:


arr = np.linspace(1, 10, 10)

bool_index = arr > 5


print("Original Array:")
print(arr)
print(bool_index)

print("\nElements greater than 5:")
print(arr[bool_index])


Original Array:
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[False False False False False  True  True  True  True  True]

Elements greater than 5:
[ 6.  7.  8.  9. 10.]


In [100]:



arr = np.zeros(12)


reshaped_arr = np.reshape(arr, (3, 4))


print("Original Array:")
print(reshaped_arr)

print("Slice of the first two rows:")
print(reshaped_arr[:2])


Original Array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Slice of the first two rows:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [112]:



arr1 = np.linspace(1, 5, 5)
arr2 = np.linspace(6, 10, 5)
print(arr1)
hstacked_arr = np.hstack((arr1.reshape(-1, 1), arr2.reshape(-1, 1)))

print("Original Array:")
print(hstacked_arr)

print(hstacked_arr[:, :2])


[1. 2. 3. 4. 5.]
Original Array:
[[ 1.  6.]
 [ 2.  7.]
 [ 3.  8.]
 [ 4.  9.]
 [ 5. 10.]]
[[ 1.  6.]
 [ 2.  7.]
 [ 3.  8.]
 [ 4.  9.]
 [ 5. 10.]]


In [117]:


arr = np.random.rand(3, 3)
print("Original Array:")
print(arr)

mean_value = np.mean(arr)
median_value = np.median(arr)
std_value = np.std(arr)
variance_value = np.var(arr)

print("\nMean of the array:", mean_value)
print("Median of the array:", median_value)
print("Standard deviation of the array:", std_value)
print("Variance of the array:", variance_value)


Original Array:
[[0.20179506 0.54275598 0.03863274]
 [0.07267682 0.51372575 0.55477322]
 [0.30457887 0.17453745 0.72059097]]

Mean of the array: 0.3471185400932774
Median of the array: 0.3045788698192434
Standard deviation of the array: 0.2289659389586117
Variance of the array: 0.052425401203198704


In [118]:


arr1 = np.random.randn(3, 3)
arr2 = np.random.randn(3, 3)

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)

dot_product = np.dot(arr1, arr2)
determinant_value = np.linalg.det(arr1)
inverse_arr2 = np.linalg.inv(arr2)

print("\nDot product of Array 1 and Array 2:")
print(dot_product)
print("\nDeterminant of Array 1:")
print(determinant_value)
print("\nInverse of Array 2:")
print(inverse_arr2)


Array 1:
[[ 0.963203    0.36134327  1.00256416]
 [ 0.06308358  1.57903507 -0.94227132]
 [-0.83971211  0.43594453  0.65834058]]

Array 2:
[[-0.38743479 -1.90328367 -0.32142019]
 [-1.92836274 -0.77465004 -0.18790643]
 [ 0.12904226  0.568784    0.09325779]]

Dot product of Array 1 and Array 2:
[[-0.94060612 -1.54292066 -0.28399469]
 [-3.19098599 -1.87921439 -0.40486132]
 [-0.43037175  1.63495949  0.24937904]]

Determinant of Array 1:
3.024760967199947

Inverse of Array 2:
[[   3.18775141   -0.4898723     9.9997812 ]
 [  14.31956252    0.49197454   50.34476593]
 [ -91.74667967   -2.3227338  -310.16917037]]


In [119]:



random_array = np.random.rand(3, 3)
print("Random Array (Uniform Distribution):")
print(random_array)


Random Array (Uniform Distribution):
[[0.7304433  0.32854524 0.33464479]
 [0.31550935 0.93249018 0.05219822]
 [0.3968728  0.2754413  0.87576072]]


In [120]:



random_array = np.random.randn(3, 3)
print("Random Array (Standard Normal Distribution):")
print(random_array)


Random Array (Standard Normal Distribution):
[[-1.29166909  0.03950853 -1.71332759]
 [-1.41185874 -2.79362946  0.20016125]
 [-0.09903645 -1.67692064  1.69300675]]


In [121]:



random_array = np.random.randint(0, 10, size=(3, 3))
print("Random Array (Integers between 0 and 10):")
print(random_array)


Random Array (Integers between 0 and 10):
[[9 4 4]
 [7 7 7]
 [2 2 6]]


In [123]:


np.random.seed(1)


random_array = np.random.rand(3, 3)
print("Random Array with Seed (Uniform Distribution):")
print(random_array)


Random Array with Seed (Uniform Distribution):
[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]


In [124]:



arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 2, 1, 4, 5])


equal_result = np.equal(arr1, arr2)
not_equal_result = np.not_equal(arr1, arr2)
less_result = np.less(arr1, arr2)
greater_result = np.greater(arr1, arr2)


print("Array 1:", arr1)
print("Array 2:", arr2)
print("\nElement-wise Equal:", equal_result)
print("Element-wise Not Equal:", not_equal_result)
print("Element-wise Less Than:", less_result)
print("Element-wise Greater Than:", greater_result)


Array 1: [1 2 3 4 5]
Array 2: [3 2 1 4 5]

Element-wise Equal: [False  True False  True  True]
Element-wise Not Equal: [ True False  True False False]
Element-wise Less Than: [ True False False False False]
Element-wise Greater Than: [False False  True False False]


In [125]:



arr = np.array([1, 2, 3, 4, 5])


condition = arr < 3


result = np.where(condition, arr, 10)


print("Original Array:", arr)
print("Condition:", condition)
print("Result:", result)


Original Array: [1 2 3 4 5]
Condition: [ True  True False False False]
Result: [ 1  2 10 10 10]


In [126]:



arr = np.array([1, 2, 2, 3, 3, 4, 4, 5])

unique_elements = np.unique(arr)

print("Original Array:", arr)
print("Unique Elements:", unique_elements)


Original Array: [1 2 2 3 3 4 4 5]
Unique Elements: [1 2 3 4 5]
